# SimpleU User Preferences File
# Arrange & Choice: Kwok
# 上午 10:05 2014/11/24 星期一
# pref(key,value) 会覆盖默认设置,在删除之后会恢复默认设置.
# user_pref(key,value)等同于从about:config修改,删除之后,修改的设置仍然有效.

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("browser.cache.disk.parent_directory", "C:\\Windows\\Temp\\Cache");
user_pref("browser.cache.offline.parent_directory", "C:\\Windows\\Temp\\OfflineCache");
user_pref("browser.contentHandlers.types.5.title", "豆瓣九点");
user_pref("browser.contentHandlers.types.5.type", "application/vnd.mozilla.maybe.feed");
user_pref("browser.contentHandlers.types.5.uri", "http://9.douban.com/reader/subscribe?url=%s");
user_pref("browser.contentHandlers.types.6.title", "抓虾");
user_pref("browser.contentHandlers.types.6.type", "application/vnd.mozilla.maybe.feed");
user_pref("browser.contentHandlers.types.6.uri", "http://www.zhuaxia.com/add_channel.php?url=%s");
user_pref("browser.contentHandlers.types.7.title", "哪吒");
user_pref("browser.contentHandlers.types.7.type", "application/vnd.mozilla.maybe.feed");
user_pref("browser.contentHandlers.types.7.uri", "http://inezha.com/add?url=%s");
user_pref("browser.contentHandlers.types.8.title", "NetVibes");
user_pref("browser.contentHandlers.types.8.type", "application/vnd.mozilla.maybe.feed");
user_pref("browser.contentHandlers.types.8.uri", "http://www.netvibes.com/subscribe.php?url=%s");
user_pref("browser.contentHandlers.types.9.title", "Tiny RSS");
user_pref("browser.contentHandlers.types.9.type", "application/vnd.mozilla.maybe.feed");
user_pref("browser.contentHandlers.types.9.uri", "http://your.domain.dom/url-to-tt-rss/backend.php?op=pref-feeds&subop=add&feed_url=%s&quiet=1&from=firefox");
user_pref("browser.ctrlTab.previews", true);
user_pref("browser.download.manager.alertOnEXEOpen", false);
user_pref("browser.newtab.url", "chrome://mynewtab/content/index.html");
user_pref("browser.rights.3.shown", false);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.openintab", true);
user_pref("browser.search.update", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "chrome://mynewtab/content/index.html");
user_pref("browser.startup.page", 3);
user_pref("browser.tabs.animate", false);
user_pref("browser.tabs.closeWindowWithLastTab", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnCloseOtherTabs", false);
user_pref("browser.warnOnQuit", false);
user_pref("browser.xul.error_pages.expert_bad_cert", true);
user_pref("datareporting.healthreport.pendingDeleteRemoteData", true);
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("dom.event.contextmenu.enabled", false);
user_pref("dom.ipc.plugins.processLaunchTimeoutSecs", 5);
user_pref("dom.ipc.plugins.timeoutSecs", 5);
user_pref("dom.max_chrome_script_run_time", 5);
user_pref("dom.max_script_run_time", 5);
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("general.useragent.locale", "zh-CN");
user_pref("general.warnOnAboutConfig", false);
user_pref("intl.accept_languages","zh-cn,zh,zh-hk,zh-tw,zh-sg,en-us,en,en-gb,ja");
user_pref("intl.charset.detector", "universal_charset_detector");
user_pref("intl.charsetmenu.browser.cache", "UTF-8, windows-1252, EUC-JP, gbk");
user_pref("layout.spellcheckDefault", 0);
user_pref("middlemouse.contentLoadURL", true);
user_pref("middlemouse.paste", true);
user_pref("middlemouse.scrollbarPosition", true);
user_pref("mousewheel.acceleration.start", 3);
user_pref("mousewheel.withnokey.numlines", 7);
user_pref("mousewheel.withnokey.sysnumlines", false);
user_pref("network.cookie.cookieBehavior", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("plugins.hide_infobar_for_missing_plugin", true);
user_pref("plugins.hide_infobar_for_outdated_plugin", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.OCSP.enabled", 0);
user_pref("security.default_personal_cert", "Select Automatically");
user_pref("security.dialog_enable_delay", 0);
user_pref("security.mixed_content.block_active_content", false);
user_pref("signed.applets.codebase_principal_support", true);
user_pref("signon.importedFromSqlite", true);
user_pref("signon.overrideAutocomplete", true);
user_pref("browser.search.defaultenginename", "谷歌");
user_pref("browser.search.selectedEngine", "谷歌");
user_pref("startup.homepage_welcome_url", "http://bbs.kafan.cn/forum-215-1.html");
user_pref("toolkit.telemetry.rejected", true);
user_pref("view_source.editor.external", true);
user_pref("xpinstall.whitelist.required", false);
user_pref("plugin.state.np-mswmp", 2);
user_pref("plugin.state.np_115upload_plugin", 2);
user_pref("plugin.state.npactivex", 2);
user_pref("plugin.state.npalicdo", 2);
user_pref("plugin.state.npalidcp", 2);
user_pref("plugin.state.npaliedit", 2);
user_pref("plugin.state.npalisecctrl", 2);
user_pref("plugin.state.npalissologin", 2);
user_pref("plugin.state.npcmbedit", 2);
user_pref("plugin.state.npgoogleupdate", 0);
user_pref("plugin.state.npqqcert", 2);
user_pref("plugin.state.npqqedit", 2);
user_pref("plugin.state.npssoaxctrlforptlogin", 2);
user_pref("plugin.state.npuploader", 2);
user_pref("plugin.state.npuploadplugin", 2);
user_pref("plugin.state.npwangwang", 2);
user_pref("plugin.state.npwebplayer", 2);
user_pref("plugin.state.npxfweb", 2);
user_pref("plugin.state.npxgax", 2);
user_pref("plugin.state.npyunwebdetect", 1);
user_pref("addMenu.FILE_PATH", "lib\\_addMenu.js ");
user_pref("extensions.firegestures.mousetrail.color", "#999999");
user_pref("extensions.firegestures.mousetrail.size", 13);
user_pref("extensions.greasemonkey.installDelay", 0);
user_pref("extensions.greasemonkey.stats.prompted", true);
user_pref("extensions.lastpass.hidecontextmenu", true);
user_pref("extensions.lastpass.rememberPassword", true);
user_pref("extensions.lastpass.disableffpwasked", true);
user_pref("extensions.proxyselector.clear.cookies", false);
user_pref("extensions.proxyselector.display.button.icontext", "icon");
user_pref("extensions.uacontrol.actions", "@DEFAULT=@NORMAL 163.com=@NORMAL 360.cn=Mozilla/5.0%20(Windows%20NT%206.1)%20QIHU%20360SE bilibili.com=@NORMAL browser.qq.com=Mozilla/5.0%20(Windows%20NT%206.1)%20Chrome/38 ccb.com.cn=@NORMAL cmbchina.com=@NORMAL ebook.tianya.cn=@NORMAL facebook.com=@NORMAL fqgoogle.com=@NORMAL hd.baofeng.com=Mozilla/5.0%20(iPad;%20CPU%20OS%208_1_1%20like%20Mac%20OS%20X) ifeng.com=@NORMAL kafan.cn=@NORMAL ltaaa.com=@NORMAL m.sm.cn=Mozilla/5.0%20(Windows%20NT%206.1)%20UCBrowser/9.9 mp.weixin.qq.com=mozilla/5.0%20(linux;%20u;%20android%204.1.2;%20zh-cn;%20mi-one%20plus%20build/jzo54k)%20applewebkit/534.30%20(khtml,%20like%20gecko)%20version/4.0%20mobile%20safari/534.30%20micromessenger/5.0.1.352 mybank.icbc.com.cn=Mozilla/5.0%20(Windows%20NT%206.1)%20Firefox/11 mybank1.icbc.com.cn=Mozilla/5.0%20(Windows%20NT%206.1)%20Firefox/11 pan.baidu.com=netdisk;5;PC;PC-Windows;6;WindowsBaiduYunGuanJia pinterest.com=@NORMAL qq.com=Mozilla/5.0%20(Windows%20NT%206.1)%20QQBrowser sainsburys.co.uk=@NORMAL skype.com=Opera/9.9%20(Windows%20NT%206.1;%20U;%20en) smzdm.com=@NORMAL userstyles.org=@NORMAL vip.icbc.com.cn=Mozilla/5.0%20(Windows%20NT%206.1)%20Firefox/11 vip1.icbc.com.cn=Mozilla/5.0%20(Windows%20NT%206.1)%20Firefox/11 vod.kankan.com=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2011_1) wap.baidu.com=Mozilla/5.0%20(Windows%20NT%206.1)%20UCBrowser/9.9 wapp.baidu.com=Mozilla/5.0%20(iPod;%20CPU%20iPhone%20OS%208_1_1%20like%20Mac%20OS%20X)%20 www.icbc.com.cn=Mozilla/5.0%20(Windows%20NT%206.1)%20Firefox/11 www.yto.net.cn=@NORMAL");
user_pref("userChromeJS.InspectElement.contentType", 1);
user_pref("userChromeJS.InspectElement.mainWinType", 2);
